spring.application.name=API-GATEWAY
server.port=8080

# ===============================
# EUREKA CONFIGURATION
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# Route 1 - Auth Service
#spring.cloud.gateway.routes[0].id=AUTH-SERVER
#spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVER
#spring.cloud.gateway.routes[0].predicates[0]=Path=/auth-server/**
#spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Route for Auth Service
spring.cloud.gateway.routes[0].id=AUTH-SERVER
spring.cloud.gateway.routes[0].uri=http://localhost:8085
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth-server/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

# Route 2 - Account Service
spring.cloud.gateway.routes[1].id=ACCOUNT-SERVICE
spring.cloud.gateway.routes[1].uri=lb://ACCOUNT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/account/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

# Route 2 - Transaction Service
spring.cloud.gateway.routes[2].id=TRANSACTION-SERVICE
spring.cloud.gateway.routes[2].uri=lb://TRANSACTION-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/transaction/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

# Enable service discovery routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Jwt
security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b

spring.main.allow-bean-definition-overriding=true
spring.config.info = true

# Enable insecure trust manager (only for dev/testing with self-signed cert)
spring.cloud.gateway.httpclient.ssl.use-insecure-trust-manager=true
